### ISSUE TITLE
Install on Windows, target 32bit applications 

### ISSUE THREAD

**Issue by Dediggefedde** [jordanvrtanoski/luacpp#13]
I want to use the library in a 32-bit project on Windows using the C++ Builder of Embarcadero.
However, I have trouble "installing" the library. 

My first attempt was following the instruction on Windows. 
I installed CMake, Lua, and MinGW for Windows, but MinGW does not know the -j parameter. 
The CMake command generated a Microsoft Visual Studio project that I could open but failed when trying to compile.

Then I tried to use the WSL subsystem to install it in Linux(Ubuntu). It installs (with two errors), but I can only see ".a" library files.
I copied the .a libraries and include files to windows and tried to compile the example program for 32bit and 64bit executables in the C++ Builder Community edition. In both cases, the linker complained there were "unresolved external" luacpp-commands, indicating the library is not read properly.

Can you please give a pointer on how to install/use the library in Windows?
Or perhaps even include the compiled binaries in the release on GitHub?

**Comment by jordanvrtanoski** [comment]
First and foremost, you are not able to use libraries compiled for linux under windows (and vice-versa). To be able to use the LuaCPP library in the Win32 project you need to compile it yourself with C++ Builder. The general steps would be:
- Locate a Lua library (preferably Lua 5.3) for Win32 (`.lib` or `.dll` file)
- Create a library project in C++ Builder (either static package or dynamic link library)
- Add the sources of the LuaCPP library to the library project located in the `Source` folder of this repository
- Build the package
Once you compile the library for Win32 you will get the `.lib` file conatining the static library and/or `.dll` containing the dynamic link library.
