### ISSUE TITLE
Accessing variables created in a Lua file in another Lua file

### ISSUE THREAD

**Issue by hlpdev** [jordanvrtanoski/luacpp#14]
I know the title may sound confusing, but I'll explain. So I am making a modding system for my game that uses LUA. Each mod gets their own LUA environment but each script in the mod uses the same Lua environment. My problem is, someone is trying to create a Config.lua script, which is ran first, then they try to access a variable defined there in Mod.lua, which is ran after the Config.lua script is ran. An error gets spit out saying that the variable is not defined. 

*First Script Ran (Config.lua):*
```lua
MessageToSend = "This is the best mod to ever be created for SCPCBR"
```

*Second Script Ran (Mod.lua):*
```lua
scp.console_log(MessageToSend)
```

Keep in mind that both scripts are being ran in order on the same Lua environment. Also the error has nothing to do with the scp.console_log() method as I made a custom library for that. I'm not sure how I can make this work as I'm not too familiar with this library. Any help would be great, thanks!

**Comment by jordanvrtanoski** [comment]
Hi, 
Looking from the host application perspective, there are two types of variables: 
- Global environment variables and the 
- Local environment variables.

The local environment variables are the variables created by the scripts running in the LUA engine and are not transferable between sessions. The local variables (the variables that are not defined in the environment or in the context) will be lost on the subsequent invocation of the `Run()` method. Therefore in your case, the second script will not be aware of the variables that the first script created/modified. 

The global environment variables are the variables (C++ objects) that are shared between the host application while the local environment variables are the variables that are created by LUA engine during the run-time.

The LuaCPP library provides ability to register the global variables with the `LuaEnvironment` object and use this object to run a script in a context with `LuaContext::RunWithEnvironment()`. When invoked in the `RunWithEnvironment`, the `LuaEnvironment` object will populate the LUA context with the global variables before the execution, and will collect their values after the execution.

What this means is that you need to register the `MessageToSend` as part of the `LuaEnvironment` so you can transfer the states in multiple contexts.

Check the unit test from `TEST_F(TestLuaContext, TestGlobalVariables)` and `TEST_F(TestLuaContext, TestEnvironmentVariables)` from the `Source/UnitTest/TestLuaContext.cpp` for example how to use the environment variables.

In case you want to make a more dynamic library for the end user, you can use the `LuaTTable` as a base to hold the dynamically created variables from the script. For more details see `TEST_F(TestLuaTypes, TestLuaTypesBridgeToLua)` from the `Source/UnitTest/TestLuaTypes.cpp`. To do this, you will create a `LuaTTable` object and register it in the `LuaEnvironment` under a specific name (ex. `game_context`) as follows:

In the host application

```
LuaContext ctx;
LuaEnvironment env;
std::shared_ptr<Engine::LuaTTable> tbl = std::make_shared<Engine::LuaTTable>();
env["game_context"] = tbl;
...
...
...
ctx.RunWithEnvironment(compiled_script, env);
```

The users will than use in the first script:

```
game_context.MessageToSend = "This is the best mod to ever be created for SCPCBR"
```

and in the second script:
```
scp.console_log(game_context.MessageToSend)
```

**Comment by hlpdev** [comment]
I really appreciate the response! This helped me out a lot. Thank you.
