### ISSUE TITLE
AddCFunction replace-flag can't be working

### ISSUE THREAD

**Issue by Kuurusch** [jordanvrtanoski/luacpp#19]
I've encountered, that in case the flag "replace" is true, your code tries just to replace the cfunction with an insert. But insert will not overwrite en entry in a map, if it already exists by definition. So I've modified your code to make it work. Would you like, that I provide it to you and how?

Sidenote:
I've modified your library also in the way, that it's possible now to overwrite an existing standard-library, or only certain functions/methods of the library and it is even possible to create a library with the OO-Style of LUA.

**Comment by jordanvrtanoski** [comment]
Thank you for the PR. Wonderfull addition to the library. I have merged it.

**Comment by Kuurusch** [comment]
Your welcome, your library helped me a lot. What I've didn't do yet is an easy mechanism to add and use lua-object atributes. Thats the only missing part of the library at the moment
